INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"


# Evaluation datasets
GRABCUT_PATH: "/home/cota/EMC-Click/datasets/GrabCut"
BERKELEY_PATH: "/home/cota/EMC-Click/datasets/Berkeley"
DAVIS_PATH:  "//home/cota/EMC-Click/datasets/DAVIS"


# Train datasets
SBD_PATH:  "/home/dufei.df/data/segmentation/SBD/dataset"
COCO_PATH: "/home/dufei.df/data/segmentation/COCO"
LVIS_PATH: "/home/dufei.df/data/segmentation/LVIS"
LVIS_v1_PATH: "/home/dufei.df/data/segmentation/COCO_LVIS"
OPENIMAGES_PATH: "/home/xizhi.cx/data/dataset/OpenImage"
ADE20K_PATH: "/home/dufei.df/data/segmentation/ADE20K"

# Extra options for training
THINOBJECT_PATH: "/home/dufei.df/data/segmentation/ThinObject5K"
MSRA10K_PATH: "/home/dufei.df/data/segmentation/MSRA10K_Imgs_GT/Imgs"
DUT_TR_PATH: "/home/dufei.df/data/segmentation/DUTS-TR/DUTS-TR-Image"
DUT_TE_PATH: "/home/dufei.df/data/segmentation/DUTS-TE/DUTS-TE-Image"
YTBVOS_PATH: "/home/dufei.df/data/segmentation/YTBVOS"
HFLICKER_PATH: "/home/dufei.df/data/segmentation/HFlickr"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./weights/hrnet_w18_small_model_v2.pth"
  HRNETV2_W18: "./weigths/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "/home/cota/EMC-Click/weights/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "/home/cota/EMC-Click/weights/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "/home/cota/EMC-Click/weights/hrnetv2_w48_imagenet_pretrained.pth"











